# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-api-docs}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2010-06-29}
  s.description = %q{Create documentation for an API built in Sinatra.}
  s.email = %q{ddollar@gmail.com}
  s.files = [
    "Rakefile",
     "lib/sinatra/api_docs.rb",
     "lib/sinatra/api_docs/viewer.rb",
     "lib/sinatra/api_docs/views/documentation.sass",
     "lib/sinatra/api_docs/views/layout.haml",
     "lib/sinatra/api_docs/views/page.haml",
     "lib/sinatra/api_docs/views/toc.haml",
     "spec/sinatra/api_docs_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://daviddollar.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Create documentation for an API built in Sinatra.}
  s.test_files = [
    "spec/sinatra/api_docs_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.5"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.0.12"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.0"])
    else
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.5"])
      s.add_dependency(%q<haml>, ["~> 3.0.12"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_dependency(%q<sinatra>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.5"])
    s.add_dependency(%q<haml>, ["~> 3.0.12"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    s.add_dependency(%q<sinatra>, ["~> 1.0"])
  end
end

